name: API breaking changes

on:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.7
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # https://github.com/actions/checkout/issues/766
    - name: Mark the workspace as safe
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
    - name: API breaking changes
      run: |
        swift package diagnose-api-breaking-changes origin/${GITHUB_BASE_REF}