
name: Tests
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - swift:5.4
          - swift:5.5
          - swift:5.6
          - swift:5.7
    container:
      image: ${{ matrix.tag }}
    
    steps:
    - uses: actions/checkout@v3
    - run: swift test
    env:
      SBPLATFORM_APP_ID: 123456
      SBPLATFORM_APP_SECRET: secret_test
      SBPLATFORM_ENCRYPTION_KEY: encryption_key

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: swift test
    env:
      SBPLATFORM_APP_ID: 123456
      SBPLATFORM_APP_SECRET: secret_test
      SBPLATFORM_ENCRYPTION_KEY: encryption_key      