
name: Tests
on:
  workflow_dispatch:
  push:
    branches: [ "mastet" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    container:
      image: swift:5.7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: swift test
    env:
      SBPLATFORM_APP_ID: 123456
      SBPLATFORM_APP_SECRET: secret_test
      SBPLATFORM_ENCRYPTION_KEY: encryption_key

  test_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: swift test
    env:
      SBPLATFORM_APP_ID: 123456
      SBPLATFORM_APP_SECRET: secret_test
      SBPLATFORM_ENCRYPTION_KEY: encryption_key      